name: check
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    name: otp ${{matrix.otp}}
    strategy:
      matrix:
        otp: [18.3, 19.3, 20.3, 21.3, 22.3, 23.1]
    steps:

      - uses: actions/checkout@v2.0.0

      - uses: gleam-lang/setup-erlang@v1.1.0
        with:
          otp-version: ${{matrix.otp}}

      - run: make

      - run: ./rebar3 coveralls send
