name: check
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    name: otp ${{matrix.otp}}
    strategy:
      matrix:
        otp: [21.3, 22.3, 23.1]
    steps:

      - uses: actions/checkout@v2.0.0

      - uses: gleam-lang/setup-erlang@v1.1.0
        with:
          otp-version: ${{matrix.otp}}

      - run: make

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: _build/test/cover/ct.coverdata

      # - run: ./rebar3 coveralls send
